"""initial_tables

Revision ID: 5cd2e320f79b
Revises: 
Create Date: 2026-08-14 20:49:10.644863

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cd2e320f79b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('BACHELOR', 'OWNER', 'ADMIN', 'SUPER_ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('institution_or_company', sa.String(length=150), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'PUSH', name='notification_channel_enum'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('properties',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('property_type', sa.Enum('FLAT', 'SUBLET', 'MESS', 'HOSTEL', name='property_type_enum'), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('area_neighborhood', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('flat_number', sa.String(length=50), nullable=True),
    sa.Column('has_lift', sa.Boolean(), nullable=False),
    sa.Column('has_generator', sa.Boolean(), nullable=False),
    sa.Column('has_cctv', sa.Boolean(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('gate_closing_time', sa.String(length=50), nullable=True),
    sa.Column('visitor_policy', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_verified_by_admin', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_area_neighborhood'), 'properties', ['area_neighborhood'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_is_published'), 'properties', ['is_published'], unique=False)
    op.create_index(op.f('ix_properties_is_verified_by_admin'), 'properties', ['is_verified_by_admin'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_table('roommate_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('smoking_allowed', sa.Boolean(), nullable=False),
    sa.Column('sleep_schedule', sa.String(length=50), nullable=False),
    sa.Column('cleanliness_level', sa.Integer(), nullable=False),
    sa.Column('guests_allowed', sa.Boolean(), nullable=False),
    sa.Column('dietary_preference', sa.String(length=50), nullable=False),
    sa.Column('study_habit', sa.String(length=50), nullable=False),
    sa.Column('additional_notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roommate_preferences_id'), 'roommate_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_roommate_preferences_user_id'), 'roommate_preferences', ['user_id'], unique=True)
    op.create_table('user_kyc',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'PENDING', 'APPROVED', 'REJECTED', name='kyc_status_enum'), nullable=False),
    sa.Column('document_type', sa.Enum('NID', 'PASSPORT', 'BIRTH_CERTIFICATE', 'STUDENT_ID', 'EMPLOYEE_ID', name='kyc_document_type_enum'), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('front_document_url', sa.String(length=512), nullable=False),
    sa.Column('back_document_url', sa.String(length=512), nullable=True),
    sa.Column('student_or_work_id_url', sa.String(length=512), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('raw_verification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_kyc_id'), 'user_kyc', ['id'], unique=False)
    op.create_index(op.f('ix_user_kyc_status'), 'user_kyc', ['status'], unique=False)
    op.create_index(op.f('ix_user_kyc_user_id'), 'user_kyc', ['user_id'], unique=True)
    op.create_table('emergency_alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('SECURITY_INTRUDER', 'MEDICAL', 'FIRE', 'HARASSMENT', 'ACCIDENT', 'OTHER', name='emergency_type_enum'), nullable=False),
    sa.Column('emergency_message', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_alerts_id'), 'emergency_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_alerts_is_active'), 'emergency_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_emergency_alerts_user_id'), 'emergency_alerts', ['user_id'], unique=False)
    op.create_table('notices',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notice_priority_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.create_index(op.f('ix_notices_property_id'), 'notices', ['property_id'], unique=False)
    op.create_table('property_media',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('media_url', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_media_id'), 'property_media', ['id'], unique=False)
    op.create_index(op.f('ix_property_media_property_id'), 'property_media', ['property_id'], unique=False)
    op.create_table('rooms',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_number_or_name', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.Enum('SINGLE', 'MASTER', 'SHARED', name='room_type_enum'), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('security_deposit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('has_attached_bathroom', sa.Boolean(), nullable=False),
    sa.Column('has_balcony', sa.Boolean(), nullable=False),
    sa.Column('has_ac', sa.Boolean(), nullable=False),
    sa.Column('is_furnished', sa.Boolean(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_is_available'), 'rooms', ['is_available'], unique=False)
    op.create_index(op.f('ix_rooms_property_id'), 'rooms', ['property_id'], unique=False)
    op.create_table('notice_reads',
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_reads_id'), 'notice_reads', ['id'], unique=False)
    op.create_index(op.f('ix_notice_reads_notice_id'), 'notice_reads', ['notice_id'], unique=False)
    op.create_index(op.f('ix_notice_reads_user_id'), 'notice_reads', ['user_id'], unique=False)
    op.create_table('room_seats',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('seat_identifier', sa.String(length=50), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_seats_id'), 'room_seats', ['id'], unique=False)
    op.create_index(op.f('ix_room_seats_is_occupied'), 'room_seats', ['is_occupied'], unique=False)
    op.create_index(op.f('ix_room_seats_room_id'), 'room_seats', ['room_id'], unique=False)
    op.create_table('bookings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=True),
    sa.Column('booking_status', sa.Enum('REQUESTED', 'APPROVED_BY_OWNER', 'REJECTED', 'DEPOSIT_PAID', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='booking_status_enum'), nullable=False),
    sa.Column('requested_move_in_date', sa.Date(), nullable=False),
    sa.Column('token_deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('owner_remarks', sa.String(length=500), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['room_seats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_status'), 'bookings', ['booking_status'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_property_id'), 'bookings', ['property_id'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_seat_id'), 'bookings', ['seat_id'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_table('tenancies',
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=True),
    sa.Column('agreed_monthly_rent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('agreed_security_deposit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lease_start_date', sa.Date(), nullable=False),
    sa.Column('lease_end_date', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NOTICE_SERVED', 'TERMINATED', 'EVICTED', name='tenancy_status_enum'), nullable=False),
    sa.Column('agreement_status', sa.Enum('DRAFT', 'PENDING_SIGNATURE', 'SIGNED', 'EXPIRED', name='agreement_status_enum'), nullable=False),
    sa.Column('digital_agreement_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['room_seats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_tenancies_id'), 'tenancies', ['id'], unique=False)
    op.create_index(op.f('ix_tenancies_owner_id'), 'tenancies', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tenancies_property_id'), 'tenancies', ['property_id'], unique=False)
    op.create_index(op.f('ix_tenancies_room_id'), 'tenancies', ['room_id'], unique=False)
    op.create_index(op.f('ix_tenancies_seat_id'), 'tenancies', ['seat_id'], unique=False)
    op.create_index(op.f('ix_tenancies_status'), 'tenancies', ['status'], unique=False)
    op.create_index(op.f('ix_tenancies_tenant_id'), 'tenancies', ['tenant_id'], unique=False)
    op.create_table('complaints',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('tenancy_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('PLUMBING', 'ELECTRICAL', 'APPLIANCE', 'STRUCTURAL', 'INTERNET', 'SECURITY', 'NOISE', 'CLEANLINESS', 'OTHER', name='complaint_category_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY', name='complaint_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REOPENED', name='complaint_status_enum'), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repair_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_bearer', sa.String(length=50), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenancy_id'], ['tenancies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_property_id'), 'complaints', ['property_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_tenant_id'), 'complaints', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('tenancy_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('billing_month_year', sa.String(length=7), nullable=False),
    sa.Column('base_rent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('electricity_bill', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('water_bill', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gas_bill', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('internet_bill', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_adjustments', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('late_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='invoice_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenancy_id'], ['tenancies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenancy_id', 'billing_month_year', name='uq_tenancy_billing_month')
    )
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_tenancy_id'), 'invoices', ['tenancy_id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('reviews',
    sa.Column('tenancy_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewee_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenancy_id'], ['tenancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_is_public'), 'reviews', ['is_public'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'), 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_tenancy_id'), 'reviews', ['tenancy_id'], unique=False)
    op.create_table('payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('MOCK', 'BKASH', 'NAGAD', 'ROCKET', 'SSLCOMMERZ', 'BANK_TRANSFER', 'CASH', name='payment_method_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='payment_status_enum'), nullable=False),
    sa.Column('payment_gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_reference'), 'payments', ['transaction_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_reviews_tenancy_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_is_public'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenancy_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_complaints_tenant_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_property_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_tenancies_tenant_id'), table_name='tenancies')
    op.drop_index(op.f('ix_tenancies_status'), table_name='tenancies')
    op.drop_index(op.f('ix_tenancies_seat_id'), table_name='tenancies')
    op.drop_index(op.f('ix_tenancies_room_id'), table_name='tenancies')
    op.drop_index(op.f('ix_tenancies_property_id'), table_name='tenancies')
    op.drop_index(op.f('ix_tenancies_owner_id'), table_name='tenancies')
    op.drop_index(op.f('ix_tenancies_id'), table_name='tenancies')
    op.drop_table('tenancies')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_seat_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_property_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_status'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_room_seats_room_id'), table_name='room_seats')
    op.drop_index(op.f('ix_room_seats_is_occupied'), table_name='room_seats')
    op.drop_index(op.f('ix_room_seats_id'), table_name='room_seats')
    op.drop_table('room_seats')
    op.drop_index(op.f('ix_notice_reads_user_id'), table_name='notice_reads')
    op.drop_index(op.f('ix_notice_reads_notice_id'), table_name='notice_reads')
    op.drop_index(op.f('ix_notice_reads_id'), table_name='notice_reads')
    op.drop_table('notice_reads')
    op.drop_index(op.f('ix_rooms_property_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_is_available'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_property_media_property_id'), table_name='property_media')
    op.drop_index(op.f('ix_property_media_id'), table_name='property_media')
    op.drop_table('property_media')
    op.drop_index(op.f('ix_notices_property_id'), table_name='notices')
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_emergency_alerts_user_id'), table_name='emergency_alerts')
    op.drop_index(op.f('ix_emergency_alerts_is_active'), table_name='emergency_alerts')
    op.drop_index(op.f('ix_emergency_alerts_id'), table_name='emergency_alerts')
    op.drop_table('emergency_alerts')
    op.drop_index(op.f('ix_user_kyc_user_id'), table_name='user_kyc')
    op.drop_index(op.f('ix_user_kyc_status'), table_name='user_kyc')
    op.drop_index(op.f('ix_user_kyc_id'), table_name='user_kyc')
    op.drop_table('user_kyc')
    op.drop_index(op.f('ix_roommate_preferences_user_id'), table_name='roommate_preferences')
    op.drop_index(op.f('ix_roommate_preferences_id'), table_name='roommate_preferences')
    op.drop_table('roommate_preferences')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_verified_by_admin'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_published'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_area_neighborhood'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
